// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "currency", Type: field.TypeEnum, Enums: []string{"USD"}, Default: "USD"},
		{Name: "total", Type: field.TypeInt64, Default: 0},
		{Name: "is_open", Type: field.TypeBool, Default: true},
		{Name: "closed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
	}
	// LineItemsColumns holds the columns for the "line_items" table.
	LineItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "price", Type: field.TypeInt64},
		{Name: "quantity", Type: field.TypeInt64},
		{Name: "added_at", Type: field.TypeTime},
		{Name: "bill_line_items", Type: field.TypeString, Nullable: true},
	}
	// LineItemsTable holds the schema information for the "line_items" table.
	LineItemsTable = &schema.Table{
		Name:       "line_items",
		Columns:    LineItemsColumns,
		PrimaryKey: []*schema.Column{LineItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "line_items_bills_line_items",
				Columns:    []*schema.Column{LineItemsColumns[5]},
				RefColumns: []*schema.Column{BillsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BillsTable,
		LineItemsTable,
	}
)

func init() {
	LineItemsTable.ForeignKeys[0].RefTable = BillsTable
}
