// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dsha256/feesapi/entity/bill"
	"github.com/dsha256/feesapi/entity/lineitem"
	"github.com/dsha256/feesapi/entity/predicate"
	"github.com/google/uuid"
)

// LineItemQuery is the builder for querying LineItem entities.
type LineItemQuery struct {
	config
	ctx        *QueryContext
	order      []lineitem.OrderOption
	inters     []Interceptor
	predicates []predicate.LineItem
	withOwner  *BillQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LineItemQuery builder.
func (liq *LineItemQuery) Where(ps ...predicate.LineItem) *LineItemQuery {
	liq.predicates = append(liq.predicates, ps...)
	return liq
}

// Limit the number of records to be returned by this query.
func (liq *LineItemQuery) Limit(limit int) *LineItemQuery {
	liq.ctx.Limit = &limit
	return liq
}

// Offset to start from.
func (liq *LineItemQuery) Offset(offset int) *LineItemQuery {
	liq.ctx.Offset = &offset
	return liq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (liq *LineItemQuery) Unique(unique bool) *LineItemQuery {
	liq.ctx.Unique = &unique
	return liq
}

// Order specifies how the records should be ordered.
func (liq *LineItemQuery) Order(o ...lineitem.OrderOption) *LineItemQuery {
	liq.order = append(liq.order, o...)
	return liq
}

// QueryOwner chains the current query on the "owner" edge.
func (liq *LineItemQuery) QueryOwner() *BillQuery {
	query := (&BillClient{config: liq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := liq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := liq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lineitem.Table, lineitem.FieldID, selector),
			sqlgraph.To(bill.Table, bill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, lineitem.OwnerTable, lineitem.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(liq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LineItem entity from the query.
// Returns a *NotFoundError when no LineItem was found.
func (liq *LineItemQuery) First(ctx context.Context) (*LineItem, error) {
	nodes, err := liq.Limit(1).All(setContextOp(ctx, liq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lineitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (liq *LineItemQuery) FirstX(ctx context.Context) *LineItem {
	node, err := liq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LineItem ID from the query.
// Returns a *NotFoundError when no LineItem ID was found.
func (liq *LineItemQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = liq.Limit(1).IDs(setContextOp(ctx, liq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lineitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (liq *LineItemQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := liq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LineItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LineItem entity is found.
// Returns a *NotFoundError when no LineItem entities are found.
func (liq *LineItemQuery) Only(ctx context.Context) (*LineItem, error) {
	nodes, err := liq.Limit(2).All(setContextOp(ctx, liq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lineitem.Label}
	default:
		return nil, &NotSingularError{lineitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (liq *LineItemQuery) OnlyX(ctx context.Context) *LineItem {
	node, err := liq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LineItem ID in the query.
// Returns a *NotSingularError when more than one LineItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (liq *LineItemQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = liq.Limit(2).IDs(setContextOp(ctx, liq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lineitem.Label}
	default:
		err = &NotSingularError{lineitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (liq *LineItemQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := liq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LineItems.
func (liq *LineItemQuery) All(ctx context.Context) ([]*LineItem, error) {
	ctx = setContextOp(ctx, liq.ctx, "All")
	if err := liq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LineItem, *LineItemQuery]()
	return withInterceptors[[]*LineItem](ctx, liq, qr, liq.inters)
}

// AllX is like All, but panics if an error occurs.
func (liq *LineItemQuery) AllX(ctx context.Context) []*LineItem {
	nodes, err := liq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LineItem IDs.
func (liq *LineItemQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if liq.ctx.Unique == nil && liq.path != nil {
		liq.Unique(true)
	}
	ctx = setContextOp(ctx, liq.ctx, "IDs")
	if err = liq.Select(lineitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (liq *LineItemQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := liq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (liq *LineItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, liq.ctx, "Count")
	if err := liq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, liq, querierCount[*LineItemQuery](), liq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (liq *LineItemQuery) CountX(ctx context.Context) int {
	count, err := liq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (liq *LineItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, liq.ctx, "Exist")
	switch _, err := liq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entity: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (liq *LineItemQuery) ExistX(ctx context.Context) bool {
	exist, err := liq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LineItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (liq *LineItemQuery) Clone() *LineItemQuery {
	if liq == nil {
		return nil
	}
	return &LineItemQuery{
		config:     liq.config,
		ctx:        liq.ctx.Clone(),
		order:      append([]lineitem.OrderOption{}, liq.order...),
		inters:     append([]Interceptor{}, liq.inters...),
		predicates: append([]predicate.LineItem{}, liq.predicates...),
		withOwner:  liq.withOwner.Clone(),
		// clone intermediate query.
		sql:  liq.sql.Clone(),
		path: liq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (liq *LineItemQuery) WithOwner(opts ...func(*BillQuery)) *LineItemQuery {
	query := (&BillClient{config: liq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	liq.withOwner = query
	return liq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LineItem.Query().
//		GroupBy(lineitem.FieldName).
//		Aggregate(entity.Count()).
//		Scan(ctx, &v)
func (liq *LineItemQuery) GroupBy(field string, fields ...string) *LineItemGroupBy {
	liq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LineItemGroupBy{build: liq}
	grbuild.flds = &liq.ctx.Fields
	grbuild.label = lineitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.LineItem.Query().
//		Select(lineitem.FieldName).
//		Scan(ctx, &v)
func (liq *LineItemQuery) Select(fields ...string) *LineItemSelect {
	liq.ctx.Fields = append(liq.ctx.Fields, fields...)
	sbuild := &LineItemSelect{LineItemQuery: liq}
	sbuild.label = lineitem.Label
	sbuild.flds, sbuild.scan = &liq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LineItemSelect configured with the given aggregations.
func (liq *LineItemQuery) Aggregate(fns ...AggregateFunc) *LineItemSelect {
	return liq.Select().Aggregate(fns...)
}

func (liq *LineItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range liq.inters {
		if inter == nil {
			return fmt.Errorf("entity: uninitialized interceptor (forgotten import entity/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, liq); err != nil {
				return err
			}
		}
	}
	for _, f := range liq.ctx.Fields {
		if !lineitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
		}
	}
	if liq.path != nil {
		prev, err := liq.path(ctx)
		if err != nil {
			return err
		}
		liq.sql = prev
	}
	return nil
}

func (liq *LineItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LineItem, error) {
	var (
		nodes       = []*LineItem{}
		withFKs     = liq.withFKs
		_spec       = liq.querySpec()
		loadedTypes = [1]bool{
			liq.withOwner != nil,
		}
	)
	if liq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, lineitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LineItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LineItem{config: liq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, liq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := liq.withOwner; query != nil {
		if err := liq.loadOwner(ctx, query, nodes, nil,
			func(n *LineItem, e *Bill) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (liq *LineItemQuery) loadOwner(ctx context.Context, query *BillQuery, nodes []*LineItem, init func(*LineItem), assign func(*LineItem, *Bill)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*LineItem)
	for i := range nodes {
		if nodes[i].bill_line_items == nil {
			continue
		}
		fk := *nodes[i].bill_line_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bill_line_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (liq *LineItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := liq.querySpec()
	_spec.Node.Columns = liq.ctx.Fields
	if len(liq.ctx.Fields) > 0 {
		_spec.Unique = liq.ctx.Unique != nil && *liq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, liq.driver, _spec)
}

func (liq *LineItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lineitem.Table, lineitem.Columns, sqlgraph.NewFieldSpec(lineitem.FieldID, field.TypeUUID))
	_spec.From = liq.sql
	if unique := liq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if liq.path != nil {
		_spec.Unique = true
	}
	if fields := liq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lineitem.FieldID)
		for i := range fields {
			if fields[i] != lineitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := liq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := liq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := liq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := liq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (liq *LineItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(liq.driver.Dialect())
	t1 := builder.Table(lineitem.Table)
	columns := liq.ctx.Fields
	if len(columns) == 0 {
		columns = lineitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if liq.sql != nil {
		selector = liq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if liq.ctx.Unique != nil && *liq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range liq.predicates {
		p(selector)
	}
	for _, p := range liq.order {
		p(selector)
	}
	if offset := liq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := liq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LineItemGroupBy is the group-by builder for LineItem entities.
type LineItemGroupBy struct {
	selector
	build *LineItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ligb *LineItemGroupBy) Aggregate(fns ...AggregateFunc) *LineItemGroupBy {
	ligb.fns = append(ligb.fns, fns...)
	return ligb
}

// Scan applies the selector query and scans the result into the given value.
func (ligb *LineItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ligb.build.ctx, "GroupBy")
	if err := ligb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LineItemQuery, *LineItemGroupBy](ctx, ligb.build, ligb, ligb.build.inters, v)
}

func (ligb *LineItemGroupBy) sqlScan(ctx context.Context, root *LineItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ligb.fns))
	for _, fn := range ligb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ligb.flds)+len(ligb.fns))
		for _, f := range *ligb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ligb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ligb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LineItemSelect is the builder for selecting fields of LineItem entities.
type LineItemSelect struct {
	*LineItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lis *LineItemSelect) Aggregate(fns ...AggregateFunc) *LineItemSelect {
	lis.fns = append(lis.fns, fns...)
	return lis
}

// Scan applies the selector query and scans the result into the given value.
func (lis *LineItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lis.ctx, "Select")
	if err := lis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LineItemQuery, *LineItemSelect](ctx, lis.LineItemQuery, lis, lis.inters, v)
}

func (lis *LineItemSelect) sqlScan(ctx context.Context, root *LineItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lis.fns))
	for _, fn := range lis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
